### ISSUE TITLE
【已分配】词云

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#12]
<img width="203" alt="arvin004" src="https://user-images.githubusercontent.com/21328793/162150886-a347ffee-c2fd-495e-86cc-e2e5b594a9bd.png">
**效果描述：**

1. 词云可显示不同的形状；
2. 可显示每项的提示框且可调整显示位置；
3. 可自适应不同分辨率；
4. 文字可配置不同的角度显示；

**配置描述：**

1. 提示框是否显示；
2. 提示框显示位置；
3. 提示框边框类型；
4. 提示框边框宽度；
5. 提示框背景颜色；
6. 提示框是否只显示在图表区域；
7. 网格线显示隐藏；
8. 图表区域大小；
9. 图表区背景颜色；
10. 词云字体大小范围；
11. 词云显示位置；
12. 词云画布宽度和高度；
13. 是否渲染超出画布的文字；
14. 文字是否随机颜色；
15. 文字类型选择；
16. 超长文字显示方式；
17. 字体粗细；
18. 字体风格选择；
19. 字体是否显示阴影；
20. 字体模糊程度；

**数据格式描述：**

```json
{
	code: 200,
	msg: "success",
	data: [
    {
      "name": "……",
      "value": 120
    }
  ]
}
```

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

已将任务分配给您，期待您贡献的组件，有看到您想要认领了多个任务，方便的话可加小助手微信沟通后续奖金发放流程，微信号：xiaoyuerwise

**Comment by soulferryman** [comment]
此任务已经重新释放，欢迎其他开发者认领

**Comment by muhunwang** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取任务

@muhunwang 已将任务分配给您
