### ISSUE TITLE
Echarts热力图

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#14]
![rlt](https://user-images.githubusercontent.com/21328793/162151952-33a27212-748b-4602-bfb9-8804ce2e75b0.png)
一款好用的拓扑图针对不同需求、不同用户使用，在定制化方面可拓展；实现上可变下可扩；

**期望配置：**

1. 热力图grid配置（上下左右百分比）；
2. --是否显示grid坐标系网格
3. --grid的层级大小
4. --网格颜色选择
5. --是否上传网格背景图片
6. --图表阴影颜色
7. --图表阴影大小
8. --图表阴影颜色
9. --图表阴影颜色xy偏差值
10. tooltip是否启用
11. --启用后触发类型
12. --弹框是否跟随鼠标移动OR鼠标某个位置
13. --是否自定义弹框内容（代码块）
14. --提示框背景颜色
15. --提示框边框颜色
16. --提示框间距
17. --提示框文本样式自定义（代码块）
18. 坐标系可选择（二维坐标系 or 地理坐标系）
19. --地理坐标系
20. --热力图点大小配置
21. --热力图点模糊代销可大小
22. --设置最大透明度
23. --设置最小透明度
24. 二维直角坐标系
25. --是否开启label标签
26. --标签位置（上下左右）
27. --标签距离热力图点距离
28. --标签是都旋转默认0，文本框
29. --文本颜色
30. --文本粗细
31. --文本风格
32. --文字大小
33. --文字居中31
34. itemStyle图形样式
35. --图形颜色
36. --图形边颜色
37. --图形边大小
38. --图形边类型（solid、dashed、dotted）
39. --图形透明度
40. --图形阴影效果配置
41. --图形阴影颜色
42. --图形阴影偏移量
43. 是否开启高亮模式
44. --是否淡出其它数据的图形已达到聚焦的效果
45. visualMapContinuous连续映射组件关联
46. --最小值
47. --最大值
48. --对应值位置文本框
49. --拖拽手柄是否显示
50. --拖拽是否实时更新
51. --拖拽手柄宽
52. --拖拽守斌高
53. --坐标系是否反转
54. x轴数据文本框
55. y轴数据文本框
56. data数据文本框

**数据格式：**

```json
[
    [0, 0, 5],
    [1, 0, 1],
    [2, 0, '-'],
    [3, 0, '-'],
    [4, 0, '-'],
    [5, 0, '-'],
    [6, 0, '-'],
    [7, 0, '-'],
    [8, 0, '-'],
    [9, 0, '-'],
    [10, 0, '-']
]
```

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

已将任务分配给您，期待您贡献的组件，有看到您想要认领了多个任务，方便的话可加小助手微信沟通后续奖金发放流程，微信号：xiaoyuerwise
