### ISSUE TITLE
MapBox地图

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#16]
![mapBox](https://user-images.githubusercontent.com/21328793/162152341-a6a755fe-2db9-480d-9173-e414b375936d.png)
**期望效果：**

1. 支持导入地图数据
2. 支持嵌入Three模型（多个，上图不够精准，类似于机房）
3. 支持直接在地图上开发Dom
4. 支持动画跳转、相机放大缩小等

**期望配置：**

1. 坐标点
  1. 地图

    - 默认中心点
    - 默认缩放级别
    - 默认旋转角度
    - 默认俯视角度
    - 天空盒样式
    - 初次渲染是否带有动画

    2. 模型

    - 默认大小
    - 支持跟随地图的缩放级别变化大小
    - 默认坐标位置（渲染在地图上的节点位置）
    - 默认旋转角度

2. 交互
  3. 地图

    - 支持鼠标放大于缩小
    - 支持鼠标拖拽旋转
    - 地图右下角有归位按钮（可以恢复最初时的位置）

    2. 模型

    - 点击跳转动画（模型与模型之间的跳转）
    - 是否需要自动旋转
    - 自动旋转速度
    - 自动旋转方向

    3. Dom

    - 支持写除了模型之外的其他div
    - div可以设置坐标点，附着在地图的某个位置之上。
    - div内的文本颜色
    - div内的文本大小
    - div内的文本风格

3. 基础文字配置（可用在模型顶部的名字和自定义div）
  4. 文本

    - 文本宽度
    - 文本高度
    - 背景色
    - 内边距
    - 外边距

    2. 字体

    - 是否显示
    - 字体粗细
    - 字体大小
    - 字体颜色
    - 字体风格
    - 字体类型
    - 字体行高
    - 字体省略方式
    - 字体阴影

    3. 边框

    - 是否显示
    - 边框颜色
    - 边框宽度
    - 边框风格
    - 内边距
    - 外边距

4. 画线
  5. 在地图上

    - 地图上的某个区域需要标注，提供(XY数据格式标注出来，类似于区域标识）
    - 标注颜色
    - 标注风格
    - 区域内有小气泡提示
    - 气泡提示内的文本
    - 气泡提示文本风格
    - 气泡提示文本大小
    - 气泡提示文本颜色

**数据格式：**

```json
 [
    {key:'dom', data:[]}, 
    {key:'three', data:[]}, 
    {key:'mapbox', data:[]}
]
```

**Comment by songhn233** [comment]
I would like to work on this issue. Maybe you can assign it to me~
