### ISSUE TITLE
自旋转球体

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#17]
![qxz](https://user-images.githubusercontent.com/21328793/162152519-75a77429-5cad-49f6-98d5-3c393fe332eb.png)
**期望效果：**

1. 支持自动旋转
2. 支持根据数据改变状态
3. 支持鼠标拖拽
4. 支持鼠标经过某个框之后显示小气泡

**期望配置：**

1. 球体基础文本配置
  1. 文本

    - 文本宽度
    - 文本高度
    - 背景色
    - 内边距
    - 外边距

    2. 字体

    - 是否显示
    - 字体粗细
    - 字体大小
    - 字体颜色
    - 字体风格
    - 字体类型
    - 字体行高
    - 字体省略方式
    - 字体阴影

    3. 边框

    - 是否显示
    - 边框颜色
    - 边框宽度
    - 边框风格
    - 内边距
    - 外边距
    - 鼠标经过边框颜色

2. 底部和侧边样式
  3. 底部框

    - 底部的框框支持旋转
    - 底部的框框有水波纹效果
    - 底部的框框支持更换图片
    - 底部的框框支持div写法
    - 底部的框框支持旋转方向
    - 底部的框框支持鼠标经过停止

    2. 左边状态
       - 左边状态是否显示
       - 状态细粒度
       - 状态文本内容
       - 状态文字颜色
       - 状态背景色
       - 状态边框样式
       - 状态内容小气泡
    3. 右侧数据
       - 数据综合是否显示
       - 背景图片支持更换
       - 模块背景色
       - 文字大小
       - 文字颜色
       - icon图片上传
  4. 整体配置
    5. 球体

    - 是否需要自动旋转
    - 是否支持鼠标拖拽
    - 自动旋转方向
    - 自动旋转速度
    - 光波效果

    2. 小气泡

    - 鼠标经过正方体是否弹出小气泡
    - 小气泡是否显示
    - 小气泡背景色
    - 小气泡是否圆角
    - 小气泡边框宽度
    - 小气泡边框类型

    3. 事件

    - 点击抛出事件

**数据格式：**

```json
 {
    xAxis: [],
    data: [
      {
        "id": 1,
        "spvCode": "app2",
        "capCode": "cap1,cap2,cap5,cap11,cap20",
        "appName": "新柜面系统",
        "appStatus": "0",
        "transCount": 422,
        "duration": 5027.99,
        "rrRate": 97.16,
        "succRate": 85.85,
        "updateTime": "2021-08-25T21:50:47"
      },
      {
        "id": 2,
        "spvCode": "app2",
        "capCode": "cap1,cap2,cap5,cap11,cap20",
        "appName": "柜面向ESB发送的业务",
        "appStatus": "0",
        "transCount": 433,
        "duration": 5027.99,
        "rrRate": 97.16,
        "succRate": 85.85,
        "updateTime": "2021-08-25T21:50:47"
      }
    ]
  }
```

**Comment by Rosso-Wang** [comment]
1

**Comment by yanchaomei** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务
已将任务分配给您，期待您贡献的组件，感谢您对飞鱼组件库的关注

**Comment by soulferryman** [comment]
> 我要领取任务

**Comment by soulferryman** [comment]
> 我要领取任务

@yanchaomei  hello，有看到您还没有提交这个组件的PR，请问是在开发过程中遇到了什么问题么，可以联系小助手咨询，微信：xiaoyuerwise

**Comment by soulferryman** [comment]
@yanchaomei hello，开发过程中有问题可以联系小助手咨询哈，微信：xiaoyuerwise，如果长时间延期任务我们将在最近释放该任务供其他开发者领取

**Comment by soulferryman** [comment]
@yanchaomei hello，如果您在本周五之前没有联系小助手，或者提交这个任务的组件，我们就释放此任务了哈

**Comment by soulferryman** [comment]
此任务已释放，其他开发者可领取

**Comment by soulferryman** [comment]
此任务已释放，其他开发者可领取
