### ISSUE TITLE
【已分配】自定义仪表盘

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#2]
![自定义仪表盘的副本](https://user-images.githubusercontent.com/21328793/162134837-cda4bbd9-ea6f-464e-8e14-e37034842729.png)

1. 效果图：如上
2. 效果描述：表盘根据返回数据百分比动态展示指针方位，数据刷新时需要支持增量或减量转动指针，中央数字动态增加或减少，具体见效果图
3. 配置描述：
    1）表盘最高值可根据返回数据动态变化；
    2）数据更新时指针转动速度可自定义，支持自定义指针背景图片；
    3）单位文字、字体样式、字体颜色、字体大小、字体字重支持自定义；
    4）中央数字字体样式、字体颜色、字体大小、字体字重支持自定义，且能配置最大能展示多少位；
4. 数据格式描述：
{"dataMax":200,"data":180}

**Comment by mojinxiaowei-li** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取任务

已将任务分配给您，期待您贡献的组件

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

抱歉，此任务已有人领取，并经与开发者沟通，已将快开发完毕，为避免重复造轮子，就不将该任务分给您了，感谢您对飞鱼组件库的关注

**Comment by dick000** [comment]
我来了我来了，我要认领任务。

**Comment by soulferryman** [comment]
> 我来了我来了，我要认领任务。

这个任务已经有人领取了，大佬要不要看看这个

**Comment by dick000** [comment]
摸金校尉给我了，他忙别的事情了，和管理员说了啊。

**Comment by soulferryman** [comment]
> 摸金校尉给我了，他忙别的事情了，和管理员说了啊。

get，已经将这个任务的issue分配给你了
