### ISSUE TITLE
组件开发规范.md 中的链接打不开

### ISSUE THREAD

**Issue by Neeke** [CloudWise-OpenSource/FlyFishComponents#21]
https://github.com/CloudWise-OpenSource/FlyFishComponents/blob/main/docs/%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%A7%84%E8%8C%83.md

更新开发规范为完整内容。或更新 http://docs.aiops.cloudwise.com/zh/flyfish/design.html 中的为完整内容。

**Comment by soulferryman** [comment]
@all-contributors please add @Neeke  for doc
