### ISSUE TITLE
自定义日历

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#3]
![自定义日历](https://user-images.githubusercontent.com/21328793/162138259-b89fde29-05ab-445a-bec2-a3ca8c371c8b.png)
1. 效果图：如上
2. 效果描述：可配置长宽格子数、x\y轴展示方位，格子展示支持"\n"换行，定时顺序切换格子高亮状态，对应有类似tooltip动态展示格子详细数据，内容也支持"\n"换行，具体见效果图
3. 配置描述：
    1）长宽格子数量、格子长宽、边框粗细颜色以及格内文字的字体样式、字体颜色、字体大小、字体字重支持自定义；
    2）x\y轴展示方位（上下左右）、字体样式、字体颜色、字体大小、字体字重支持自定义；
    3）类tooltip展示框背景、宽度、高度、字体样式、字体颜色、字体大小、字体字重支持自定义，；
    4）定时切换时间支持自定义，为0则不切换，高亮颜色支持自定义；
    5）支持配置此刻高亮颜色，即nowData，颜色支持自定义；
4. 数据格式描述：
{"xAxis":["a","b","c","d"],"yAxis":["一","二","三",],"nowData":{"x":"a","y":"一"},"data":[[{"name":"1\n初四","content":"今天最好出门\n晒太阳"},{"name":"2\n初五","content":"计划要好好学习"},{"name":"3\n初六","content":"计划..."},{"name":"4\n初七","content":"可能下雨"}],[{"name":"5\n初八","content":"大吉\n可能解封"},{},{},{}]]}

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
此任务已经重新释放，欢迎其他开发者认领
