### ISSUE TITLE
【已分配】自定义漏斗

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#4]
![自定义漏斗图](https://user-images.githubusercontent.com/21328793/162138399-82a24269-4360-42c8-b1e8-eea5282fada9.png)

1. 效果图：如上
2. 效果描述：可配置最大高度，以及上宽、下宽，以各层高度值展示当前容量百分比，有类似tooltip弹出框展示详细数据，内容支持"\n"换行，具体见效果图（每层字体这里未显示）
3. 配置描述：
    1）上宽、下宽、最大高度支持自定义；
    2）各层展示文字排布方式、字体样式、字体颜色、字体大小、字体字重支持自定义，文字格式可根据返回数据自定义配置；
    3）类tooltip展示框背景、宽度、高度、字体样式、字体颜色、字体大小、字体字重支持自定义；
    4）各层颜色支持使用rgba格式自定义，高亮颜色支持自定义；
    5）背景图片支持自定义（换成水杯？）；
    6）模块定位相对父DOM位置支持配置调整top、left；
    7）层边界粗细、颜色可自定义，层之间支持设置过渡色，可自定义过渡带高，为0则没有；
    8）加分项：更好的话支持传入clip-path自定义整体图形样式；
4. 数据格式描述：
{"percent":0.88,"data":[[{"name":"江水","percent":0.10,"content":"水质较差，味道不好，不宜食用"},{"name":"海水","percent":0.70,"content":"水质较好，味道太咸，不宜食用"},{"name":"井水","percent":0.20,"content":"水质不错，味道可以，适宜食用"}]}

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

已将任务分配给您，期待您贡献的组件，有看到您想要认领了多个任务，方便的话可加小助手微信沟通后续奖金发放流程，微信号：xiaoyuerwise

**Comment by sakurajiajia** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

@sakurajiajia 已将该任务分配给您，期待您贡献的组件，有任何问题请联系小助手咨询，微信号：xiaoyuerwise
