### ISSUE TITLE
雨量图

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#6]
![雨量图](https://user-images.githubusercontent.com/21328793/162138854-7e4c61b0-d1fe-40b9-92b4-0003f21069ad.png)
1. 效果图：如上
2. 效果描述：双x、双y轴，两x\y轴分别相对放置，两个系列相对倒挂，具体见效果图
3. 配置描述：
    1）各系列颜色可自定义；
    2）tooltip的背景可自定义；
    3）x\y轴字体样式、字体颜色、字体大小、字体字重及线条粗细、颜色可自定义设置；
    4）图例样式、位置可自定义；
4. 数据格式描述：
{"xAxis":["10:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00"],"data":[{"name":"降水量","data":[99,80,110,40,60,147,120,90,80,150,140,110]},{"name":"流速","data":[0.5,0.5,1.5,8.5,7.5,11.5,10.5,11.5,8.5,9.5,10.5,7.5]}]}

**Comment by faga1** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取任务

已将任务分配给您，期待您贡献的组件

**Comment by soulferryman** [comment]
> 我要领取任务

我们已经收到您提交的组件pr，非常感谢您对于飞鱼开源社区的付出！组件写得非常完美，都符合我们提出的要求，除了其中对于tooltip背景图的自定义设置这块缺失，请您抽空加上！再次感谢您对于社区的贡献！

**Comment by maxkasd** [comment]
我要领取该任务

**Comment by soulferryman** [comment]
> 我要领取该任务

抱歉，此任务已有人领取，并经与开发者沟通，已提交初版pr，在做最后的修改，为避免重复造轮子，就不将该任务分给您了，感谢您对飞鱼组件库的关注
