### ISSUE TITLE
FlyFish开发者现金激励计划

### ISSUE THREAD

**Issue by soulferryman** [CloudWise-OpenSource/FlyFishComponents#7]
FlyFish是云智慧开源、社区驱动的数据可视化编排项目，我们欢迎来自社区的各种贡献，目前我们已经启动了FlyFish组件贡献者计划，您所开发的组件将帮助更多使用FlyFish的开发者，我们将定期邀请已贡献的Contributor成为FlyFish的核心开发者，FlyFish下一个版本有什么功能将由你来决定

为了更好激励开发者贡献FlyFish组件，我们推出了**现金激励计划**，完成相关组件开发，除了FlyFish贡献者证书及周边礼物外，还会有一笔现金奖励。虽然金额不多，但是我们希望可以更好的帮您融入FlyFish开发者社区，与我们一起打造最好用的数据可视化编排平台

### 活动流程

- 在相关任务issue中回复我要领取该任务
- 管理员将任务分配给您
- 根据issue中描述的任务要求开发组件
- 将组件代码以PR方式提交到FlyFishComponments代码库中
- PR被merge后，**添加小助手微信xiaoyuerwise，备注飞鱼组件贡献者**，或发送邮件至open.source@cloudwise.com
- 领取贡献者证书与奖金

### 贡献指南

在您开始开发组件前，请一定要阅读[Readme](https://github.com/CloudWise-OpenSource/FlyFishComponents/blob/main/README.md)文档，以便您更方便的开发FlyFish的组件，在您提交PR时，请同时将 PR 链接到相应的 issue。

### 激励金额

我们将任务分为了Easy、Normal、Hard三个等级，不同级别的任务对应不同的金额，详情如下所示

Easy：500元
Normal：800元
Hard：1500元

### 任务开发周期

任务领取以第一个人领取时间为准，同一个任务只能由一人领取，开发周期内，若任务没有被完成，则该任务将自动被释放，由下一个人领取，不同任务开发周期如下所示

Easy：7天
Normal：10天
Hard：15天

### 现金激励任务列表

**Coding(Easy)**
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/2
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/3
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/4
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/6

**Coding(Normal)**
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/12

**Coding(Hard)**
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/13
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/14
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/15
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/16
- https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/17

### 活动注意事项
- 在相关Issue任务中回复【我要领取该任务】，待将该issue分配给您后，即可表示认领成功
- 每个任务只能被一个人领取，若出现多人认领同一个任务，以回复时间为准
- 认领者在对应开发周期内未完成任务时，任务将被自动释放，由其他人重新认领
- 切记用FlyFish平台来开发组件，第三方IDE开发可能会有不兼容的情况
- 最终获奖结果以Cash组件任务认领者提交PR被Merge为准，获奖后认领者需添加FlyFish官方运营同学微信添加【xiaoyuerwise】或邮件至【[open.source@cloudwise.com](mailto:open.source@cloudwise.com)】领取奖励。

### 代码提交规范
为了让您提交的PR尽快审核通过，请您在提交PR前按照此步骤审核您的代码是否符合要求

- 代码符合[组件开发规范](https://github.com/CloudWise-OpenSource/FlyFishComponents/blob/main/docs/%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%A7%84%E8%8C%83.md)

- describe.json结构
{
    compName: "value", // 组件名称
    compType: "value", // 组件类别
    contributor: "value", // 贡献者
    description: "value", // 组件描述
    iconUrl: "value",// 缩略图 存放到 组件文件夹下的images目录下
    publicTime: "value", // 组件发布时间
}

**Comment by PmcFizz** [comment]
活动只有这几个现金组件吗？ 什么时候有新的组件任务啊？ @soulferryman

**Comment by soulferryman** [comment]
> 活动只有这几个现金组件吗？ 什么时候有新的组件任务啊？ @soulferryman

目前是只有这个issue页面下的这是个任务是有现金激励的，敬请关注我们后面的计划，现在MapBox地图组件这个任务还没有人认领，大佬可以关注一下@PmcFizz

**Comment by PmcFizz** [comment]
@soulferryman  有没有没有完成，被释放的 现金奖励组件啊，我可以接啊。🤣🤣

**Comment by soulferryman** [comment]
@PmcFizz 可以加一下小助手的微信来咨询活动的详细信息哈，最近会有一些任务释放出来，微信号：xiaoyuerwise

**Comment by PmcFizz** [comment]
> @PmcFizz 这个组件任务目前还没人认领，大佬可以先搞一波这个，[Mapbox地图](https://github.com/CloudWise-OpenSource/FlyFishComponents/issues/16)

这个太复杂，地图还好， three 不太熟悉， 😅

**Comment by PmcFizz** [comment]
> @PmcFizz 可以加一下小助手的微信来咨询活动的详细信息哈，最近会有一些任务释放出来，微信号：xiaoyuerwise

已加，谢谢

**Comment by soulferryman** [comment]
@all-contributors please add @soulferryman for eventOrganizing
